version: "3.9"

networks:
  algafood-network:
    driver: bridge
    
volumes:
  algafood-mysql-data:
  
services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "mysqladmin"
    ports:
      - "3306:3306"
    networks:
      - algafood-network
    volumes:
      - algafood-mysql-data:/var/lib/mysql
  
  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      algafood.jwt.keystore.password: "123456"
    networks:
     - algafood-network
    depends_on:
      - algafood-mysql
      
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api
    